export { MedicoService } from './medico/medico.service';
export { HospitalesService } from "./hospital/hospitales.service";
export { SettigsService } from "./settigs/settigs.service";
export { SharedService } from "./share/shared.service";
export { SidebarService } from "./share/sidebar.service";
export { UsuarioService } from "./usuario/usuario.service";
export { LoginGuardGuard } from "./guards/login-guard.guard";
export { AdminGuard } from "./guards/admin.guard";
export { SubirArchivoService } from "./subirArchivo/subir-archivo.service"